### PR TITLE
Fix #30 reporter / assignee backwards

### LINKED ISSUE #30: Assignee / Reporter are backwards
Tickets say Reported by X and Assigned to Y, when in jira they are Reported by Y and Assigned to X.

### PR DESCRIPTION
**Pull request by mikeparker**
Fixes https://github.com/RobQuistNL/chrome-github-jira/issues/30

### CODE REVIEW

**Comment by RobQuistNL** [comment]
Ha, crap. I thought I had them wrong and swapped them around again. Have to pay better attention :man_facepalming: 

Thanks!

**Comment by mikeparker** [comment]
Any chance we could get this released? Thanks!

**Comment by RobQuistNL** [comment]
I'll do this tonight!

**Comment by RobQuistNL** [comment]
@mikeparker sorry, a week late :( very busy schedule.

Version 1.2.1 is released and should appear in the appstore within 60 minutes.

**Pull request merged**
